### ISSUE TITLE
UnhandledPromiseRejectionWarning: ArangoError: AQL: collection or view not found: name: /recall_skeleton_vertices (while parsing)

### ISSUE THREAD

**Issue by pecastro** [adityamukho/hivemind#14]
Whilst running the db-setup step after setting up ArangoDB and Recall I am seeing this error pop up.

```
Truncated compound_events.
(node:1275074) UnhandledPromiseRejectionWarning: ArangoError: AQL: collection or view not found: name: /recall_skeleton_vertices (while parsing)
    at new ArangoError (/home/pecastro/projects/hivemind/node_modules/arangojs/build/error.js:115:21)
    at Object.resolve (/home/pecastro/projects/hivemind/node_modules/arangojs/build/connection.js:369:32)
    at callback (/home/pecastro/projects/hivemind/node_modules/arangojs/build/connection.js:191:26)
    at IncomingMessage.<anonymous> (/home/pecastro/projects/hivemind/node_modules/arangojs/build/lib/request.node.js:108:21)
    at IncomingMessage.emit (events.js:388:22)
    at endReadableNT (internal/streams/readable.js:1336:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
(node:1275074) ArangoError: AQL: collection or view not found: name: /recall_skeleton_vertices (while parsing)
    at new ArangoError (/home/pecastro/projects/hivemind/node_modules/arangojs/build/error.js:115:21)
    at Object.resolve (/home/pecastro/projects/hivemind/node_modules/arangojs/build/connection.js:369:32)
    at callback (/home/pecastro/projects/hivemind/node_modules/arangojs/build/connection.js:191:26)
    at IncomingMessage.<anonymous> (/home/pecastro/projects/hivemind/node_modules/arangojs/build/lib/request.node.js:108:21)
    at IncomingMessage.emit (events.js:388:22)
    at endReadableNT (internal/streams/readable.js:1336:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(node:1275074) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
```

**Comment by adityamukho** [comment]
Probably the `ARANGO_SVC_MOUNT_POINT` value in `.env.local` has a leading slash. If this is so, please remove it and try. It should look like:
```
ARANGO_SVC_MOUNT_POINT=recall
```

**Comment by pecastro** [comment]
That solved it.
